/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-11 16:36:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.js\"\r\n");
      out.write("			integrity=\"sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=\"\r\n");
      out.write("			crossorigin=\"anonymous\">\r\n");
      out.write("	</script>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"Bootstrap/CSS/style1.css\">\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/13deb536c6.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).on(\"scroll\", function() {\r\n");
      out.write("			var pageTop = $(document).scrollTop();\r\n");
      out.write("			var pageBottom = pageTop + $(window).height();\r\n");
      out.write("			var tags = $(\".tag\");\r\n");
      out.write("		  \r\n");
      out.write("			for (var i = 0; i < tags.length; i++) {\r\n");
      out.write("			  var tag = tags[i];\r\n");
      out.write("			  if ($(tag).position().top < pageBottom) {\r\n");
      out.write("				$(tag).addClass(\"visible\");\r\n");
      out.write("			  } else {\r\n");
      out.write("				$(tag).removeClass(\"visible\");\r\n");
      out.write("			  }\r\n");
      out.write("			}\r\n");
      out.write("		  });\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function () {\r\n");
      out.write("			$(\"#header\").load(\"header.jsp\");\r\n");
      out.write("			$(\"#footer\").load(\"footer.html\");\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("	<title>Checkout</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"Pics/panda.png\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <div class = \"font\">\r\n");
      out.write("            <div id = \"header\"></div>\r\n");
      out.write("            <div class = \"header-adjustment\"></div>\r\n");
      out.write("            <br>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <div class = \"container-fluid\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg\">\r\n");
      out.write("                            <div class = \"Checkout-Container\">\r\n");
      out.write("                                <div class = \"Header-cart\">\r\n");
      out.write("                                    <h3 class = \"Heading-cart\">All items</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("								");
      out.print( request.getAttribute("order_list"));
      out.write("\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>  \r\n");
      out.write("                            <br>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"col-lg\">\r\n");
      out.write("                                <div class=\"Checkout-Container\">\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    <div class = \"Header-cart\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class = \"checkout-amount\" style=\"font-size:25px\">Sub-total:</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"prices tot\" style=\"font-size:25px\">0</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div style=\"text-align: center;\">Delivery charges:</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"prices\">+&nbsp&#8377;&nbsp99</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class = \"checkout-amount\">Total:</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"prices tot\">0</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"checkout-block\">\r\n");
      out.write("                                        <h1 style=\"font-size: 33px;opacity:90%\">1. Payment options</h1>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"radio-buttons\">\r\n");
      out.write("                                                <div class=\"form-check\">\r\n");
      out.write("                                                    <input class=\"form-check-input payment-radio\" type=\"radio\" name=\"Radio\" id=\"Radio1\" value=\"option1\">\r\n");
      out.write("                                                    <label class=\"payment-radio-label\" for=\"Radio1\">Cash On Delivery\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-check\">\r\n");
      out.write("                                                    <input class=\"form-check-input payment-radio\" type=\"radio\" name=\"Radio\" id=\"Radio2\" value=\"option2\">\r\n");
      out.write("                                                    <label class=\"payment-radio-label\" for=\"Radio2\">UPI / QR Code\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-check\">\r\n");
      out.write("                                                    <input class=\"form-check-input payment-radio\" type=\"radio\" name=\"Radio\" id=\"Radio3\" value=\"option2\">\r\n");
      out.write("                                                    <label class=\"payment-radio-label\" for=\"Radio3\">Net Banking\r\n");
      out.write("                                                    </label>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div id=\"payment-select\"></div>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"checkout-block\">\r\n");
      out.write("                                          <h1 style=\"font-size: 33px;opacity:90%;\">2. Delivery address</h1>\r\n");
      out.write("                                          <div class=\"delivery-address\">\r\n");
      out.write("                                            <i class=\"fa-solid fa-location-dot\"></i>\r\n");
      out.write("											");
      out.print( request.getAttribute("address"));
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"checkout-block\" style=\"text-align:center\">\r\n");
      out.write("                                        <button type=\"button\" value=\"place_order\" class=\"btn btn-warning Order\" id=\"place_order_button\" disabled>Place Order</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>            \r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("	<div id=\"footer\"></div>\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("    window.onload = calcTotal();\r\n");
      out.write("\r\n");
      out.write("    function calcTotal()\r\n");
      out.write("    {\r\n");
      out.write("        var qt = document.getElementsByClassName(\"qt\");\r\n");
      out.write("        var prices = document.getElementsByClassName(\"price\");\r\n");
      out.write("        var amt = document.getElementsByClassName(\"amount\");\r\n");
      out.write("        var tot_amount = document.getElementsByClassName(\"tot\");\r\n");
      out.write("        var amount = [];\r\n");
      out.write("        var total = 0;\r\n");
      out.write("\r\n");
      out.write("        for(var i=0; i < qt.length; i++)\r\n");
      out.write("        {\r\n");
      out.write("            amount[i] = Number(prices[i].innerHTML.slice(2)) * qt[i].innerHTML.slice(2);\r\n");
      out.write("            amt[i].innerHTML = \"&#8377;&nbsp\" + amount[i];\r\n");
      out.write("\r\n");
      out.write("            total = total + amount[i];\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tot_amount[0].innerHTML = \"&#8377;&nbsp\" + total;\r\n");
      out.write("        tot_amount[1].innerHTML = \"&#8377;&nbsp\" + (total+99);\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    var placeOrderButton = document.getElementById(\"place_order_button\");\r\n");
      out.write("    placeOrderButton.addEventListener(\"click\", checkout);\r\n");
      out.write("\r\n");
      out.write("    var paymentRadios = document.querySelectorAll(\".payment-radio\");\r\n");
      out.write("	document.getElementById(\"payment-select\").innerHTML=\"Select a payment option\";\r\n");
      out.write("	document.getElementById(\"payment-select\").style.color = \"green\";\r\n");
      out.write("	\r\n");
      out.write("	for (var i = 0; i < paymentRadios.length; i++) \r\n");
      out.write("	{\r\n");
      out.write("	    paymentRadios[i].addEventListener(\"change\", enablePlaceOrderButton);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("    var payment = \"\";\r\n");
      out.write("\r\n");
      out.write(" 	function enablePlaceOrderButton() \r\n");
      out.write(" 	{\r\n");
      out.write("	     var isChecked = false;\r\n");
      out.write("	     for (var i = 0; i < paymentRadios.length; i++) \r\n");
      out.write("	     {\r\n");
      out.write("	         if (paymentRadios[i].checked) \r\n");
      out.write("	         {\r\n");
      out.write("	             isChecked = true;\r\n");
      out.write("	             payment = document.getElementsByClassName(\"payment-radio-label\")[i].innerHTML;\r\n");
      out.write("	             break;\r\n");
      out.write("	         }\r\n");
      out.write("	     }\r\n");
      out.write("	     if (isChecked) \r\n");
      out.write("	     {\r\n");
      out.write("	        placeOrderButton.disabled = false;\r\n");
      out.write("	     	document.getElementById(\"payment-select\").innerHTML=\"\";\r\n");
      out.write("	     } \r\n");
      out.write("	     else \r\n");
      out.write("	     {\r\n");
      out.write("	         placeOrderButton.disabled = true;\r\n");
      out.write("	     }\r\n");
      out.write(" 	}\r\n");
      out.write(" 	\r\n");
      out.write(" 	function checkout()\r\n");
      out.write(" 	{\r\n");
      out.write(" 		window.location = \"Order?job=checkout\" + \"&\" + \"payment=\" + payment;      \r\n");
      out.write(" 	}\r\n");
      out.write("    </script>\r\n");
      out.write("<div id=\"footer\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
