/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-14 13:13:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class editProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.js\"\r\n");
      out.write("			integrity=\"sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=\"\r\n");
      out.write("			crossorigin=\"anonymous\">\r\n");
      out.write("	</script>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"Bootstrap/CSS/style1.css\">\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/13deb536c6.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("  <title>Edit Products</title>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).on(\"scroll\", function() {\r\n");
      out.write("			var pageTop = $(document).scrollTop();\r\n");
      out.write("			var pageBottom = pageTop + $(window).height();\r\n");
      out.write("			var tags = $(\".tag\");\r\n");
      out.write("		  \r\n");
      out.write("			for (var i = 0; i < tags.length; i++) {\r\n");
      out.write("			  var tag = tags[i];\r\n");
      out.write("			  if ($(tag).position().top < pageBottom) {\r\n");
      out.write("				$(tag).addClass(\"visible\");\r\n");
      out.write("			  } else {\r\n");
      out.write("				$(tag).removeClass(\"visible\");\r\n");
      out.write("			  }\r\n");
      out.write("			}\r\n");
      out.write("		  });\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function () {\r\n");
      out.write("			$(\"#header\").load(\"header.jsp\");\r\n");
      out.write("			$(\"#footer\").load(\"footer.html\");\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"icon\" href=\"Pics/panda.png\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <div class = \"font\">\r\n");
      out.write("            <div id = \"header\"></div>\r\n");
      out.write("            <div class = \"header-adjustment\"></div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div class=\"about\">\r\n");
      out.write("				<h2>Edit Products</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-holder\">\r\n");
      out.write("				<h2>Select the Product you wish to edit:</h2>\r\n");
      out.write("	            <br>\r\n");
      out.write("		        <div class=\"col-sm\">\r\n");
      out.write("		            <label class=\"form-label\" style=\"opacity:90%;\">Product-id</label>\r\n");
      out.write("		            <select id =\"product\" class=\"form-select\" name = \"product\" required onchange=\"getDetails()\">\r\n");
      out.write("		                <option selected value=\"\" disabled>Choose...</option>\r\n");
      out.write("		                 ");
      out.print( request.getAttribute("pid_list"));
      out.write("\r\n");
      out.write("		            </select>\r\n");
      out.write("		        </div>\r\n");
      out.write("\r\n");
      out.write("                <div id=\"product-edit\" hidden>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>                          \r\n");
      out.write("                         <div class=\"col\">\r\n");
      out.write("                             <div id=\"prod-details\" class=\"admin-text\">\r\n");
      out.write("\r\n");
      out.write("                             </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("             </div>\r\n");
      out.write("\r\n");
      out.write("		        <br>\r\n");
      out.write("		        \r\n");
      out.write("		        <div class=\"col-sm\" style=\"padding: 20px 1px;\">\r\n");
      out.write("		            <div class=\"form-floating mb-3\" >\r\n");
      out.write("		            	<!--a href=\"AdminProfile?job=delete product&pid=output\"-->\r\n");
      out.write("                       \r\n");
      out.write("		                <a href=\"AdminProfile\">\r\n");
      out.write("		                	<button class=\"btn bamboo-outline form-submit\">Back</button>\r\n");
      out.write("		                </a>\r\n");
      out.write("		            </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("		    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		function getDetails()\r\n");
      out.write("		{\r\n");
      out.write("			var pid = document.querySelector('#product').value;\r\n");
      out.write("			//document.getElementById(\"pid\").innerHTML = pid;\r\n");
      out.write("			\r\n");
      out.write("			var http = new XMLHttpRequest();\r\n");
      out.write("            http.open(\"POST\", \"AdminProfile\", true);\r\n");
      out.write("            http.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("            var params = \"pid=\" + document.querySelector('#product').value + \"&job=see one product\"; // probably use document.getElementById(...).value\r\n");
      out.write("            http.send(params);\r\n");
      out.write("            \r\n");
      out.write("            http.onreadystatechange = function() \r\n");
      out.write("            {\r\n");
      out.write("                if (http.readyState === XMLHttpRequest.DONE) \r\n");
      out.write("                {\r\n");
      out.write("                	document.getElementById(\"prod-details\").innerHTML = http.response.toString();\r\n");
      out.write("        			document.getElementById(\"product-edit\").hidden = false;\r\n");
      out.write("                }\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		 var old_value=[];\r\n");
      out.write("\r\n");
      out.write("	        function product_edit(edit_button, field_name, text_box_name)\r\n");
      out.write("			{\r\n");
      out.write("	            field = document.getElementById(field_name);\r\n");
      out.write("	            text_box = document.getElementById(text_box_name);\r\n");
      out.write("	            submit_button = edit_button.nextSibling.nextSibling;\r\n");
      out.write("\r\n");
      out.write("	            switch(field_name)\r\n");
      out.write("	            {\r\n");
      out.write("	                case \"name\": old_value[0] = field.innerHTML;\r\n");
      out.write("	                    break;\r\n");
      out.write("	                case \"price\": old_value[1] = field.innerHTML;  \r\n");
      out.write("	                    break;\r\n");
      out.write("	                case \"desc\": old_value[2] = field.innerHTML;      \r\n");
      out.write("	                    break;\r\n");
      out.write("	            }\r\n");
      out.write("				\r\n");
      out.write("				text_box.value = field.innerHTML;\r\n");
      out.write("				field.innerHTML = '';\r\n");
      out.write("				text_box.style.display = \"block\";\r\n");
      out.write("				field.style.display = \"none\";\r\n");
      out.write("				edit_button.style.display = \"none\";\r\n");
      out.write("	            submit_button.style.display = \"block\";\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	        function change_product_details(submit_button, parameter)\r\n");
      out.write("	        {\r\n");
      out.write("	            var edit_button = submit_button.previousSibling.previousSibling;\r\n");
      out.write("	            submit_button.style.display = \"none\";\r\n");
      out.write("	            edit_button.style.display = \"block\";\r\n");
      out.write("	            var http = new XMLHttpRequest();\r\n");
      out.write("	            http.open(\"POST\", \"AdminProfile\", true);\r\n");
      out.write("	            http.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("	            \r\n");
      out.write("	            switch(parameter)\r\n");
      out.write("	            {\r\n");
      out.write("	                case \"name\": console.log(old_value[0]); \r\n");
      out.write("	                    var name_textbox = document.getElementById('name-textbox');\r\n");
      out.write("	                    var name_div = name_textbox.previousSibling.previousSibling;\r\n");
      out.write("	                    if(name_textbox.value == old_value[0] || name_textbox.value ==\"\")\r\n");
      out.write("	                    {\r\n");
      out.write("	                        name_div.innerHTML = old_value[0];\r\n");
      out.write("	                    }    \r\n");
      out.write("	                    else\r\n");
      out.write("	                    {\r\n");
      out.write("	                        var params = \"job=edit product\" + \"&\" + \"name=\" + name_textbox.value + \"&\" + \"pid=\" + document.querySelector('#product').value;\r\n");
      out.write("	            	        http.send(params);\r\n");
      out.write("	                        name_div.innerHTML = name_textbox.value;\r\n");
      out.write("	                    }\r\n");
      out.write("	                    name_textbox.style.display = \"none\";\r\n");
      out.write("	                    name_div.style.display = \"block\";\r\n");
      out.write("	                    break;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	                case \"price\": console.log(old_value[1]); \r\n");
      out.write("	                    var price_textbox = document.getElementById('price-textbox');\r\n");
      out.write("	                    var price_div = price_textbox.previousSibling.previousSibling;\r\n");
      out.write("	                    \r\n");
      out.write("	                    const regex = new RegExp(/^(\\d+(?:\\.\\d{1,3})?)$/);\r\n");
      out.write("	                    console.log(regex.test(price_textbox.value)); \r\n");
      out.write("	                    \r\n");
      out.write("	                    if(price_textbox.value == old_value[1] || price_textbox.value ==\"\" || regex.test(price_textbox.value) == false)\r\n");
      out.write("	                    {\r\n");
      out.write("	                        price_div.innerHTML = old_value[1];\r\n");
      out.write("	                    }    \r\n");
      out.write("	                    else\r\n");
      out.write("	                    {\r\n");
      out.write("	                        var params = \"job=edit product\" + \"&\" + \"price=\" + price_textbox.value + \"&\" + \"pid=\" + document.querySelector('#product').value;\r\n");
      out.write("\r\n");
      out.write("	            	        http.send(params);\r\n");
      out.write("	                        price_div.innerHTML = price_textbox.value;\r\n");
      out.write("	                    }\r\n");
      out.write("	                    price_textbox.style.display = \"none\";\r\n");
      out.write("	                    price_div.style.display = \"block\";\r\n");
      out.write("	                    break;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	                case \"desc\": console.log(old_value[2]); \r\n");
      out.write("	                    var desc_textbox = document.getElementById('desc-textbox');\r\n");
      out.write("	                    var desc_div = desc_textbox.previousSibling.previousSibling;\r\n");
      out.write("	                    if(desc_textbox.value == old_value[2] || desc_textbox.value ==\"\")\r\n");
      out.write("	                    {\r\n");
      out.write("	                        desc_div.innerHTML = old_value[2];\r\n");
      out.write("	                    }    \r\n");
      out.write("	                    else\r\n");
      out.write("	                    {\r\n");
      out.write("	                        var params = \"job=edit product\" + \"&\" + \"desc=\" + desc_textbox.value + \"&\" + \"pid=\" + document.querySelector('#product').value;\r\n");
      out.write("	                        http.send(params);\r\n");
      out.write("	                        desc_div.innerHTML = desc_textbox.value;\r\n");
      out.write("\r\n");
      out.write("	                    }\r\n");
      out.write("	                    desc_textbox.style.display = \"none\";\r\n");
      out.write("	                    desc_div.style.display = \"block\";\r\n");
      out.write("	                    break;\r\n");
      out.write("	            }\r\n");
      out.write("	        }\r\n");
      out.write("		</script>\r\n");
      out.write("		<div id=\"footer\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
