/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-04 15:36:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"ISO-8859-1\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.js\"\r\n");
      out.write("			integrity=\"sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=\"\r\n");
      out.write("			crossorigin=\"anonymous\">\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).on(\"scroll\", function() {\r\n");
      out.write("			var pageTop = $(document).scrollTop();\r\n");
      out.write("			var pageBottom = pageTop + $(window).height();\r\n");
      out.write("			var tags = $(\".tag\");\r\n");
      out.write("		  \r\n");
      out.write("			for (var i = 0; i < tags.length; i++) {\r\n");
      out.write("			  var tag = tags[i];\r\n");
      out.write("			  if ($(tag).position().top < pageBottom) {\r\n");
      out.write("				$(tag).addClass(\"visible\");\r\n");
      out.write("			  } else {\r\n");
      out.write("				$(tag).removeClass(\"visible\");\r\n");
      out.write("			  }\r\n");
      out.write("			}\r\n");
      out.write("		  });\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Product List</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"Pics/panda.png\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Bootstrap/CSS/style1.css\">\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("        var prices = document.getElementsByClassName(\"list-price\");\r\n");
      out.write("        var products = document.getElementsByClassName(\"list-padding\");\r\n");
      out.write("\r\n");
      out.write("        function filter(){\r\n");
      out.write("            var selected_size = document.getElementById(\"size_filter\");\r\n");
      out.write("            var lp = document.getElementById(\"lower_price\");\r\n");
      out.write("            var up = document.getElementById(\"upper_price\");\r\n");
      out.write("            for (var i = 0; i < prices.length; i++) \r\n");
      out.write("            {\r\n");
      out.write("\r\n");
      out.write("                if(Number(up.value) < Number(lp.value)){\r\n");
      out.write("                    up.value = lp.value+\"00\";\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                if (((up.value!=\"\" || lp.value!=\"\") && Number(prices[i].innerHTML.slice(1,-14)) > Number(up.value)) || Number(prices[i].innerHTML.slice(1,-14)) < Number(lp.value) ||!products[i].dataset.sizes.includes(selected_size.value))\r\n");
      out.write("                {\r\n");
      out.write("                    \r\n");
      out.write("                    products[i].style.display=\"none\";\r\n");
      out.write("                }\r\n");
      out.write("                else {\r\n");
      out.write("                    products[i].style.display=\"block\";\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function sort()\r\n");
      out.write("    {\r\n");
      out.write("        var sort = document.getElementById(\"sort\");\r\n");
      out.write("        var http = new XMLHttpRequest();\r\n");
      out.write("        http.open(\"GET\", \"ProductList\");\r\n");
      out.write("        http.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("        var params = \"sort=\" + sort.value; // probably use document.getElementById(...).value\r\n");
      out.write("        http.send(params);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("		$(function () {\r\n");
      out.write("			$(\"#header\").load(\"header.jsp\");\r\n");
      out.write("			$(\"#footer\").load(\"footer.html\");\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"font\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div id=\"header\"></div>\r\n");
      out.write("   	    <div class=\"header-adjustment\"></div>\r\n");
      out.write("           <div class=\"product-category\">");
      out.print( request.getAttribute("category_name"));
      out.write("</div>\r\n");
      out.write("           <br>\r\n");
      out.write("           <br>\r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("                <div class=\"filters\">\r\n");
      out.write("                    <h6>Price Range</h6>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <input name=\"lower_price\" type = \"number\" class = \"form-control\"  id = \"lower_price\" min=\"100\" placeholder=\"Min.\" onchange = \"filter()\" required/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <input name=\"upper_price\" type = \"number\" class = \"form-control\"  id = \"upper_price\" min=\"100\" placeholder=\"Max. onchange = \"filter()\" required/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    \r\n");
      out.write("                    <h6>Size</h6>\r\n");
      out.write("                    <select id =\"size_filter\" class=\"form-select\" name = \"size_filter\" onchange = \"filter()\" required>\r\n");
      out.write("                        <option selected value=\"\">All</option>\r\n");
      out.write("                        <option value=\",XS,\">XS</option>\r\n");
      out.write("                        <option value=\",S,\">S</option>\r\n");
      out.write("                        <option value=\",M,\">M</option>\r\n");
      out.write("                        <option value=\",L,\">L</option>\r\n");
      out.write("                        <option value=\",XL,\">XL</option>\r\n");
      out.write("                        <option value=\",34,\">34</option>\r\n");
      out.write("                        <option value=\",35,\">35</option>\r\n");
      out.write("                        <option value=\",36,\">36</option>\r\n");
      out.write("                        <option value=\",37,\">37</option>\r\n");
      out.write("                        <option value=\",38,\">38</option>\r\n");
      out.write("                        <option value=\",39,\">39</option>\r\n");
      out.write("                        <option value=\",40,\">40</option>\r\n");
      out.write("                        <option value=\",41,\">41</option>\r\n");
      out.write("                        <option value=\",42,\">42</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                    <br>\r\n");
      out.write("                        \r\n");
      out.write("                        <h6>Order by Price</h6>\r\n");
      out.write("                        <select id =\"sort\" class=\"form-select\" name = \"sort\" onchange = \"sort()\" required>\r\n");
      out.write("                            <option selected value=\"\" disabled>All</option>\r\n");
      out.write("                            <option value=\"asc\">Low to High</option>\r\n");
      out.write("                            <option value=\"desc\">High to Low</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-10\">\r\n");
      out.write("                <div class=\"card-container\">\r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("                        ");
      out.print( request.getAttribute("product_cards"));
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<div id=\"footer\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
